name: 'Nothing but Nix'
description: 'Removes all the cruft 🪓 from a GitHub Actions runner to make the most space possible for Nix ️❄️'
branding:
  icon: 'trash-2'
  color: 'red'
inputs:
  hatchet-protocol:
    description: 'Level of file purging (Holster: none, Cleave: standard, Rampage: aggressive)'
    required: false
    default: 'cleave'
runs:
  using: composite
  steps:
    - name: The Checks
      id: environment-check
      shell: bash
      run: |
        if [ "$(lsb_release -is)" != "Ubuntu" ]; then
          echo "is_supported=false" >> $GITHUB_OUTPUT
          echo "This action only works on Ubuntu runners"
        elif [ -z "$GITHUB_ACTIONS" ]; then
          echo "is_supported=false" >> $GITHUB_OUTPUT
          echo "This action only works on GitHub Actions runner"
        elif [ -d /nix ]; then
          echo "is_supported=false" >> $GITHUB_OUTPUT
          echo "This action must be run before Nix is installed"
          exit 1
        else
          echo "is_supported=true" >> $GITHUB_OUTPUT
        fi
    - name: The Hatchet Protocol
      id: set-hatchet-protocol
      if: steps.environment-check.outputs.is_supported == 'true'
      shell: bash
      run: |
        input_protocol="${{ inputs.hatchet-protocol }}"
        # Convert to lowercase for case-insensitive comparison
        input_protocol="${input_protocol,,}"
        
        case "$input_protocol" in
          "holster")
            echo "🪓 Hatchet Protocol: Holster - Keep the hatchet sheathed, use space from /mnt (Level 0)"
            protocol_level=0;;
          "carve")
            echo "🪓 Hatchet Protocol: Carve - Craft and combine free space from / and /mnt (Level 1)"
            protocol_level=1;;
          "cleave")
            echo "🪓 Hatchet Protocol: Cleave - Make powerful, decisive cuts to large packages (Level 2)"
            protocol_level=2;;
          "rampage")
            echo "🪓 Hatchet Protocol: Rampage - Relentless, brutal elimination of all bloat (Level 3)"
            protocol_level=3;;
          *)
            echo "🪓 Hatchet Protocol: Cleave - Make powerful, decisive cuts to large packages (Level 2)"
            protocol_level=2;;
        esac

        echo "level=${protocol_level}" >> $GITHUB_OUTPUT
    - name: The Setup
      if: steps.environment-check.outputs.is_supported == 'true' && steps.set-hatchet-protocol.outputs.level > 1
      shell: bash
      run: |
        ARCH=$(uname -m)          
        if [[ "$ARCH" == "x86_64" ]]; then
          URL_ARCH="x86_64"
        elif [[ "$ARCH" == "aarch64" || "$ARCH" == "arm64" ]]; then
          URL_ARCH="aarch64"
        else
          echo "Unsupported architecture: $ARCH"
          exit 1
        fi
        
        OS=$(uname -s)
        if [[ "$OS" == "Linux" ]]; then
          URL_OS="unknown-linux-gnu"
        elif [[ "$OS" == "Darwin" ]]; then
          URL_OS="apple-darwin"
        else
          echo "Unsupported OS: $OS"
          exit 1
        fi
        
        DOWNLOAD_URL="https://github.com/SUPERCILEX/fuc/releases/download/3.0.1/${URL_ARCH}-${URL_OS}-rmz"
        curl -L -o rmz "$DOWNLOAD_URL"
        chmod +x rmz
        sudo mv rmz /usr/bin/rmz
        rmz --version
    - name: The Volume
      if: steps.environment-check.outputs.is_supported == 'true'
      shell: bash
      run: |
        # Create initial loop device using Holster approach (minimal space reclamation)
        
        free_space=$(df -m --output=avail /mnt | tail -n 1 | tr -d ' ')
        echo "Initial free space of /mnt: ${free_space}MB"
        loop_dev=$(sudo losetup --find)
        loop_num=${loop_dev##*/loop}        
        if sudo fallocate -l $((free_space - 1024))M "/mnt/disk${loop_num}.img"; then  
          sudo losetup ${loop_dev} "/mnt/disk${loop_num}.img"
        fi
          
        # Create filesystem
        sudo mkfs.btrfs -L nix -d raid0 -m raid0 --nodiscard "${loop_dev}"
        sudo btrfs device scan
        sudo btrfs filesystem show

        # Mount filesystem
        sudo mkdir -p /nix
        sudo mount LABEL=nix /nix -o noatime,nobarrier,compress=zstd:1,space_cache=v2,commit=120
        sudo df -h
        
        # Create a directory to store expansion state
        mkdir -p "${HOME}/.expansion"
        echo "Initial volume created" > "${HOME}/.expansion/holster_done"
    - name: The Purge
      if: steps.environment-check.outputs.is_supported == 'true'
      shell: bash
      run: |
        cat > /tmp/expand_nix_volume.sh << 'EOF'
        #!/bin/bash
        set -e
        
        protocol_level="${{ steps.set-hatchet-protocol.outputs.level }}"
        expansion_dir="${HOME}/.expansion"
        
        function add_expansion_disk() {
          # Check for additional free space after purging
          free_space=$(df -m --output=avail / | tail -n 1 | tr -d ' ')
          echo "Free space of / after purge: ${free_space}MB"

          # Create additional disk if at least 4GB free space exists
          if [ $free_space -gt 4096 ]; then
            # Calculate the size of the expansion disk, reserving 2GB
            disk_size=$((free_space - 2048))
            echo "Creating expansion disk of ${disk_size}MB in /"
            # Create expansion disk image
            loop_dev=$(sudo losetup --find)
            loop_num=${loop_dev##*/loop}
            if sudo fallocate -l ${disk_size}M "/disk${loop_num}.img"; then
              sudo losetup ${loop_dev} "/disk${loop_num}.img"
              
              # Add the new device to the pool
              sudo btrfs device add ${loop_dev} /nix
              echo "Added expansion disk "/disk${loop_num}.img" (${loop_dev}, ${disk_size}MB) to /nix pool" > $expansion_dir/expansion_done
              
              # Balance the filesystem to use the new space
              sudo btrfs balance start -dusage=50 /nix
              sudo btrfs filesystem show
              sudo df -h
            fi
          fi
        }

        # If carve is selected, claim space from / now
        if [[ "$protocol_level" -eq 1 ]]; then
          echo "Disk space has been carved out" > $expansion_dir/carve_done
          add_expansion_disk
        fi

        # Cleanse apt
        if [[ "$protocol_level" -ge 2 ]]; then
          sudo tee /etc/dpkg/dpkg.cfg.d/01_nocruft > /dev/null << 'APTCFG'
        path-exclude /usr/share/doc/*
        path-exclude /usr/share/fonts/*
        path-exclude /usr/share/icons/*
        path-exclude /usr/share/info/*
        path-exclude /usr/share/man/*
        APTCFG

          if [[ "$protocol_level" -ge 3 ]]; then
            sudo apt-get -y remove --purge \
              azure-cli \
              firefox \
              google-chrome-stable \
              google-cloud-sdk \
              microsoft-edge-stable \
              powershell
            sudo apt-get -y autoremove --purge
          fi

          sudo apt-get -y clean
          echo "Cleanse apt complete" > $expansion_dir/apt_done
        fi
        
        # Cleanse docker
        if [[ "$protocol_level" -ge 2 ]]; then
          for CRUFT in $(docker image ls --format '{{.ID}}'); do
            docker rmi --force "${CRUFT}" || true
          done
          docker system prune --all --force
          echo "Cleanse docker complete" > $expansion_dir/docker_done
        fi
        
        # Cleanse snap
        if [[ "$protocol_level" -ge 3 ]]; then
          sudo systemctl stop snapd.service || true
          sudo systemctl disable snapd.service || true
          sudo systemctl mask snapd.service || true
          sudo umount --recursive /snap/*/* || true
          sudo rmz -f \
            /snap \
            /usr/bin/snap* \
            /usr/lib/snapd \
            /var/snap \
            /var/lib/snapd \
            "${HOME}/snap"
          echo "Cleanse snap complete" > $expansion_dir/snap_done
        fi
        
        # Cleave
        if [[ "$protocol_level" -ge 2 ]]; then
          sudo rmz -f \
            "${HOME}/.rustup" \
            "${HOME}/.cargo" \
            "${HOME}/.dotnet" \
            /usr/local \
            /opt/hostedtoolcache \
            /opt/microsoft \
            /opt/az \
            /opt/pipx* \
            /opt/google \
            /opt/mssql-tools
          sudo mkdir -p /usr/local/{bin,doc,include,lib,man,sbin,share,src}
          echo "Cleave complete" > $expansion_dir/cleave_done
        fi
        
        # Rampage
        if [[ "$protocol_level" -ge 3 ]]; then
          sudo rmz -f \
            /usr/bin/buildah \
            /usr/bin/docker* \
            /usr/bin/java* \
            /usr/bin/kotlin* \
            /usr/bin/kubectl \
            /usr/bin/mono* \
            /usr/bin/my* \
            /usr/bin/pedump \
            /usr/bin/perror \
            /usr/bin/php* \
            /usr/bin/podman* \
            /usr/bin/ruby* \
            /usr/bin/tcpdump \
            /usr/bin/skopeo \
            /usr/bin/vim* \
            /usr/bin/x86_64-* \
            /usr/lib/*-linux-gnu/libLLVM* \
            /usr/lib/*-linux-gnu/libclang* \
            /usr/lib/*-linux-gnu/liblldb* \
            /usr/lib/*-linux-gnu/libmysql* \
            /usr/lib/cgi-bin \
            /usr/lib/dotnet \
            /usr/lib/firefox \
            /usr/lib/gcc \
            /usr/lib/google-cloud-sdk \
            /usr/lib/heroku* \
            /usr/lib/jvm \
            /usr/lib/llvm* \
            /usr/lib/mecab \
            /usr/lib/*mono* \
            /usr/lib/mysql \
            /usr/lib/php \
            /usr/lib/postgresql \
            /usr/lib/R \
            /usr/lib/ruby \
            /usr/sbin/mysql* \
            /usr/sbin/php* \
            /usr/sbin/nginx* \
            /usr/share/apache* \
            /usr/share/az* \
            /usr/share/doc/* \
            /usr/share/dotnet \
            /usr/share/fonts/* \
            /usr/share/fwupd \
            /usr/share/google-cloud-sdk \
            /usr/share/gradle* \
            /usr/share/icons/* \
            /usr/share/info/* \
            /usr/share/java \
            /usr/share/kotlin* \
            /usr/share/man/* \
            /usr/share/mecab \
            /usr/share/miniconda \
            /usr/share/mysql \
            /usr/share/postgresql \
            /usr/share/php* \
            /usr/share/python-babel-localedata \
            /usr/share/python-wheels \
            /usr/share/R \
            /usr/share/ri \
            /usr/share/sbt \
            /usr/share/swift \
            /usr/share/swig* \
            /usr/share/tcltk \
            /usr/share/texinfo \
            /usr/share/vim \
            /var/lib/gems \
            /var/lib/mecab \
            /var/lib/mysql \
            /var/lib/podman \
            /var/lib/postgresql \
            /var/lib/ubuntu-advantage
          echo "Rampage complete" > $expansion_dir/rampage_done
        fi

        # Claim the space from / for purging
        if [[ "$protocol_level" -ge 2 ]]; then
          echo "The Purge Is Complete!" > $expansion_dir/purge_done
          add_expansion_disk
        fi
        EOF

        # Make script executable and run in background
        chmod +x /tmp/expand_nix_volume.sh
        /tmp/expand_nix_volume.sh > ${HOME}/.expansion/expansion.log 2>&1 &
        echo "📈 Background space expansion started. /nix will grow as space becomes available."
        
        # Wait for the expand_nix_volume.sh process to finish
        while wait -n; do
          sleep 0.5
        done