name: Shell
on:
  workflow_dispatch:
jobs:
  debug-shell:
    name: Shell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./.github/actions/this
      - name: Run
        uses: ./.github/actions/this
      - name: Install ncdu
        run: sudo apt-get -y install ncdu
      - name: Shell
        uses: mxschmitt/action-tmate@v3
